/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Hanken Grotesk', 'sans-serif'],
      },
      colors: {
        surface: '#051425',
        'surface-dim': '#051425',
        'surface-bright': '#2c3a4d',
        'surface-container-lowest': '#010f20',
        'surface-container-low': '#0d1c2e',
        'surface-container': '#122032',
        'surface-container-high': '#1d2b3d',
        'surface-container-highest': '#283648',
        'on-surface': '#d5e3fc',
        'on-surface-variant': '#8fa3bf',
        'outline': '#918f9a',
        'outline-variant': '#47464f',
        primary: '#c1c1fc',
        'on-primary': '#2a2b5c',
        'primary-container': '#2d2e5f',
        secondary: '#ffb786',
        'on-secondary': '#502400',
        'secondary-container': '#e1730a',
        tertiary: '#f7be1d',
        'on-tertiary': '#3f2e00',
        error: '#ffb4ab',
        'on-error': '#690005',
        background: '#051425',
        'on-background': '#d5e3fc',
        'surface-variant': '#283648',
      },
      spacing: {
        'sidebar-width': '280px',
        'card-padding': '24px',
        gutter: '24px',
        'margin-desktop': '40px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
      },
    },
  },
  plugins: [],
};
